# -*- coding: utf-8 -*-
"""W3_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJrfnUfwd-KgryTbGDSuyCZM4u7BQ45c
"""

import pandas as pd
import numpy as np
#1. UPLOAD DATASET
from google.colab import files
uploaded = files.upload()

#2. LOAD DATA
df = pd.read_csv("SurveilDrone-Net23.csv")

print(df.shape)

df.head()

"""## Dataset Overview

The dataset contains UAV telemetry records including battery status,
GPS location, mission information, weather conditions,
and surveillance-related variables.
"""

#3. DATASET OVERVIEW
df.info()

"""## Missing Value Analysis

This step identifies variables containing missing values
before cleaning.
"""

#4. CHECK MISSING VALUES
df.isnull().sum()

"""## Duplicate Record Analysis"""

df.duplicated().sum()

"""## Data Type Validation"""

df.dtypes

"""#DATA CLEANING"""

#1. Covert Timestamp
df["timestamp"] = pd.to_datetime(df["timestamp"])

#2. Fix Wind Speed
negative_wind = (df["wind_speed_mps"] < 0).sum()
print("Negative wind records: ", negative_wind)
df["wind_speed_mps"] = abs(df["wind_speed_mps"])

"""## Wind Speed Validation

Negative wind speed values were converted to absolute values.
"""

#3.Check Battery Range
df["battery_level_pct"].describe()

#4. Check GPS Range
df["gps_lat"].describe()

df["gps_lon"].describe()

#5.Remove Duplicates
df = df.drop_duplicates()

"""##DSS FEATURE ENGINEERING"""

df["speed_mps"] = np.sqrt(
    df["velocity_x"]**2 +
    df["velocity_y"]**2 +
    df["velocity_z"]**2
)

# Create Battery Risk
def battery_risk(x):

    if x < 15:
        return "Critical"

    elif x < 30:
        return "High"

    elif x < 50:
        return "Medium"

    else:
        return "Low"

df["battery_risk_level"] = df["battery_level_pct"].apply(
    battery_risk
)

# Create Weather Risk
def weather_risk(x):

    if x >= 10:
        return "High"

    elif x >= 6:
        return "Medium"

    else:
        return "Low"

df["weather_risk_level"] = df["wind_speed_mps"].apply(
    weather_risk
)

def recommend(row):

    if row["battery_level_pct"] < 15:
        return "Return to Base"

    elif row["wind_speed_mps"] > 10:
        return "Delay Mission"

    else:
        return "Continue Mission"

df["recommended_action"] = df.apply(
    recommend,
    axis=1
)

# EXPORT CLEANED DATASET
df.to_csv(
    "SurveilDrone_Net23_DSS_cleaned.csv",
    index=False
)

#Download
from google.colab import files

files.download(
    "SurveilDrone_Net23_DSS_cleaned.csv"
)